CREATE DATABASE QUANLYPHONGKHAM
GO
USE QUANLYPHONGKHAM
SET DATEFORMAT dmy

CREATE TABLE PATIENT
(
	PATIENT_ID			INT		PRIMARY KEY,
	PATIENT_NAME			NVARCHAR(50),
	PATIENT_SEX				NVARCHAR(5),
	PATIENT_ADDRESS			NVARCHAR(100),
	PATIENT_PHONENUMBER		VARCHAR(13),
	PATIENT_DATEOFBIRTH		SMALLDATETIME
)

CREATE TABLE DRUG_STORAGE
(
	DRUG_STORAGE_ID			INT		PRIMARY KEY,
	DRUG_STORAGE_NAME		NVARCHAR(20),
)

CREATE TABLE DRUG_TYPE
(
	DRUG_TYPE_ID			INT		PRIMARY KEY,
	DRUG_TYPE_NAME			NVARCHAR(20),
	DRUG_TYPE_DESCRIPTION	NVARCHAR(100),
)

CREATE TABLE DRUG_STORAGE_TYPES
(
	DRUG_STORAGE_ID			INT,
	DRUG_TYPE_ID			INT,
	CONSTRAINT DST_DRUG_TYPE_ID_FK	FOREIGN KEY	(DRUG_TYPE_ID)	REFERENCES DRUG_TYPE(DRUG_TYPE_ID),
	CONSTRAINT DST_DRUG_STORAGE_ID_FK	FOREIGN KEY	(DRUG_STORAGE_ID)	REFERENCES DRUG_STORAGE(DRUG_STORAGE_ID)
)

CREATE TABLE DRUG
(
	DRUG_ID				INT		PRIMARY KEY,
	DRUG_TYPE_ID			INT,
	DRUG_NAME			NVARCHAR(50),
	DRUG_UNIT			NVARCHAR(20),
	DRUG_MANUFACTURER		NVARCHAR(30),
	DRUG_DESCRIPTION		NVARCHAR(100),
	DRUG_PRICE			MONEY
	CONSTRAINT DRUG_DRUG_TYPE_ID_FK	FOREIGN KEY	(DRUG_TYPE_ID)	REFERENCES DRUG_TYPE(DRUG_TYPE_ID)
)

CREATE TABLE DRUG_STORAGE_DATA
(
	DRUG_STORAGE_ID			INT,
	DRUG_ID				INT,
	DRUG_QUANTITY			INT,
	CONSTRAINT DSD_DRUG_ID_FK	FOREIGN KEY	(DRUG_ID)	REFERENCES DRUG(DRUG_ID),
	CONSTRAINT DSD_DRUG_STORAGE_ID_FK	FOREIGN KEY	(DRUG_STORAGE_ID)	REFERENCES DRUG_STORAGE(DRUG_STORAGE_ID)
)

CREATE TABLE SERVICE
(
	SERVICE_ID			INT		PRIMARY KEY,
	SERVICE_NAME			NVARCHAR(50),
	SERVICE_UNIT			NVARCHAR(20),
	SERVICE_PRICE			MONEY,
	SERVICE_DESCRIPTION		NVARCHAR(100)
)

CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID			INT		PRIMARY KEY,
	EMPLOYEE_NAME			NVARCHAR(50),
	EMPLOYEE_POSITION		NVARCHAR(20),
	USERNAME		NVARCHAR(20),
	PASSWORD		NVARCHAR(20),
)

CREATE TABLE EXAMINE
(
	EXAMINE_ID				INT		PRIMARY KEY,
	EMPLOYEE_ID				INT,
	PATIENT_ID				INT,
	CONSTRAINT	EXAMINE_EMPLOYEE_ID_FK	FOREIGN KEY	(EMPLOYEE_ID)	REFERENCES	EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE,
	CONSTRAINT	EXAMINE_PATIENT_ID_FK	FOREIGN KEY	(PATIENT_ID)	REFERENCES	PATIENT(PATIENT_ID) ON DELETE CASCADE
)

CREATE TABLE MEDICALRECORD
(
	MEDICALRECORD_ID			INT		PRIMARY KEY,
	EXAMINE_ID				INT,
	DATE					SMALLDATETIME,
	PATIENT_TEMP			FLOAT,
	PATIENT_WEIGHT			FLOAT,
	DIAGNOSIS				NVARCHAR(300),
	NOTE					NVARCHAR(300),
	PAYMENT_STATUS			TINYINT,
	CONSTRAINT	EXAMINE_ID_FK	FOREIGN KEY	(EXAMINE_ID)	REFERENCES EXAMINE(EXAMINE_ID) ON DELETE CASCADE
)

CREATE TABLE PRESCRIPTION
(
	MEDICALRECORD_ID			INT,
	DRUG_ID					INT,
	QUANTITY				INT,
	CONSTRAINT	PRESCRIPTION_MEDICALRECORD_ID_FK	FOREIGN KEY (MEDICALRECORD_ID)	REFERENCES MEDICALRECORD(MEDICALRECORD_ID) ON DELETE CASCADE,
	CONSTRAINT	PRESCRIPTION_DRUG_ID_FK	FOREIGN KEY (DRUG_ID)	REFERENCES DRUG(DRUG_ID),
	CONSTRAINT	PRESCRIPTION_PK	PRIMARY KEY (MEDICALRECORD_ID, DRUG_ID)
)

CREATE TABLE SERVICEBILL
(
	MEDICALRECORD_ID			INT,
	SERVICE_ID				INT,
	QUANTITY				INT,
	CONSTRAINT	SERVICEBILL_MEDICALRECORD_ID_FK	FOREIGN KEY (MEDICALRECORD_ID)	REFERENCES MEDICALRECORD(MEDICALRECORD_ID) ON DELETE CASCADE,
	CONSTRAINT	SERVICEBILL_SERVICE_ID_FK	FOREIGN KEY (SERVICE_ID)	REFERENCES SERVICE(SERVICE_ID),
	CONSTRAINT	SERVICEBILL_PK	PRIMARY KEY (MEDICALRECORD_ID, SERVICE_ID)
)

CREATE TABLE PERMISSION
(
	EMPLOYEE_ID					INT,
	
	CREATE_MEDICALRECORD		TINYINT,
	REMOVE_MEDICALRECORD		TINYINT,
	MAKEPAYMENT_MEDICALRECORD	TINYINT,
	
	EDIT_EMPLOYEE			TINYINT,
	EDIT_PATIENT			TINYINT,
	EDIT_DRUG				TINYINT,
	EDIT_SERVICE			TINYINT,
	
	CONSTRAINT	PERMISSION_EMPLOYEE_ID_FK	FOREIGN KEY (EMPLOYEE_ID)	REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE
)