CREATE DATABASE QUANLYPHONGKHAM
USE QUANLYPHONGKHAM

CREATE TABLE PATIENT
(
	PATIENT_ID			INT		PRIMARY KEY,
	PATIENT_NAME			VARCHAR(50),
	PATIENT_ADDRESS			VARCHAR(100),
	PATIENT_PHONENUMBER		VARCHAR(13),
	PATIENT_DATEOFBIRTH		SMALLDATETIME
)

CREATE TABLE DRUG_STORAGE
(
	DRUG_STORAGE_ID			INT		PRIMARY KEY,
	DRUG_STORAGE_NAME		VARCHAR(20),
)

CREATE TABLE DRUG_TYPE
(
	DRUG_TYPE_ID			INT		PRIMARY KEY,
	DRUG_TYPE_NAME			VARCHAR(20),
	DRUG_TYPE_DESCRIPTION	VARCHAR(100),
)

CREATE TABLE DRUG_STORAGE_TYPES
(
	DRUG_STORAGE_ID			INT,
	DRUG_TYPE_ID			INT,
	CONSTRAINT DST_DRUG_TYPE_ID_FK	FOREIGN KEY	(DRUG_TYPE_ID)	REFERENCES DRUG_TYPE(DRUG_TYPE_ID),
	CONSTRAINT DST_DRUG_STORAGE_ID_FK	FOREIGN KEY	(DRUG_STORAGE_ID)	REFERENCES DRUG_STORAGE(DRUG_STORAGE_ID)
)

CREATE TABLE DRUG
(
	DRUG_ID				INT		PRIMARY KEY,
	DRUG_TYPE_ID			INT,
	DRUG_NAME			VARCHAR(50),
	DRUG_UNIT			VARCHAR(20),
	DRUG_MANUFACTURER		VARCHAR(30),
	DRUG_DESCRIPTION		VARCHAR(100),
	DRUG_PRICE			MONEY
	CONSTRAINT DRUG_DRUG_TYPE_ID_FK	FOREIGN KEY	(DRUG_TYPE_ID)	REFERENCES DRUG_TYPE(DRUG_TYPE_ID)
)

CREATE TABLE DRUG_STORAGE_DATA
(
	DRUG_STORAGE_ID			INT,
	DRUG_ID				INT,
	DRUG_QUANTITY			INT,
	CONSTRAINT DSD_DRUG_ID_FK	FOREIGN KEY	(DRUG_ID)	REFERENCES DRUG(DRUG_ID),
	CONSTRAINT DSD_DRUG_STORAGE_ID_FK	FOREIGN KEY	(DRUG_STORAGE_ID)	REFERENCES DRUG_STORAGE(DRUG_STORAGE_ID)
)

CREATE TABLE SERVICE
(
	SERVICE_ID			INT		PRIMARY KEY,
	SERVICE_NAME			VARCHAR(50),
	SERVICE_UNIT			VARCHAR(20),
	SERVICE_PRICE			MONEY
)

CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID			INT		PRIMARY KEY,
	EMPLOYEE_NAME			VARCHAR(50),
	EMPLOYEE_POSITION		VARCHAR(20)
)

CREATE TABLE EXAMINE
(
	EXAMINE_ID				INT		PRIMARY KEY,
	EMPLOYEE_ID				INT,
	PATIENT_ID				INT,
	CONSTRAINT	EXAMINE_EMPLOYEE_ID_FK	FOREIGN KEY	(EMPLOYEE_ID)	REFERENCES	EMPLOYEE(EMPLOYEE_ID),
	CONSTRAINT	EXAMINE_PATIENT_ID_FK	FOREIGN KEY	(PATIENT_ID)	REFERENCES	PATIENT(PATIENT_ID)
)

CREATE TABLE MEDICALRECORD
(
	MEDICALRECORD_ID			INT		PRIMARY KEY,
	EXAMINE_ID				INT,
	DATE					SMALLDATETIME,
	DIAGNOSIS				VARCHAR(200),
	NOTE					VARCHAR(100),
	CONSTRAINT	EXAMINE_ID_FK	FOREIGN KEY	(EXAMINE_ID)	REFERENCES EXAMINE(EXAMINE_ID)
)

CREATE TABLE PRESCRIPTION
(
	MEDICALRECORD_ID			INT,
	DRUG_ID					INT,
	QUANTITY				INT,
	CONSTRAINT	PRESCRIPTION_MEDICALRECORD_ID_FK	FOREIGN KEY (MEDICALRECORD_ID)	REFERENCES MEDICALRECORD(MEDICALRECORD_ID),
	CONSTRAINT	PRESCRIPTION_DRUG_ID_FK	FOREIGN KEY (DRUG_ID)	REFERENCES DRUG(DRUG_ID),
	CONSTRAINT	PRESCRIPTION_PK	PRIMARY KEY (MEDICALRECORD_ID, DRUG_ID)
)

CREATE TABLE SERVICEBILL
(
	MEDICALRECORD_ID			INT,
	SERVICE_ID				INT,
	QUANTITY				INT,
	CONSTRAINT	SERVICEBILL_MEDICALRECORD_ID_FK	FOREIGN KEY (MEDICALRECORD_ID)	REFERENCES MEDICALRECORD(MEDICALRECORD_ID),
	CONSTRAINT	SERVICEBILL_SERVICE_ID_FK	FOREIGN KEY (SERVICE_ID)	REFERENCES SERVICE(SERVICE_ID),
	CONSTRAINT	SERVICEBILL_PK	PRIMARY KEY (MEDICALRECORD_ID, SERVICE_ID)
)